// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Full: typeof import('./src/layout/full.vue')['default']
    Layout: typeof import('./src/layout/layout.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Loadding: typeof import('./src/components/Loadding.vue')['default']
    LoadMask: typeof import('./src/components/loadMask.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Message: typeof import('./src/components/Message/message.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MyEditor: typeof import('./src/components/MyEditor.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Popper: typeof import('./src/components/Popper.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Says: typeof import('./src/components/says.vue')['default']
    TextAnimation: typeof import('./src/components/TextAnimation.vue')['default']
  }
}
